// What is javascript

/*



JavaScript is a lightweight, cross-platform, single-threaded, and interpreted compiled programming language. It is well-known for the development of web pages, and many non-browser environments also use it.

JavaScript is a weakly typed language (dynamically typed). JavaScript can be used for Client-side developments as well as Server-side developments. JavaScript is both an imperative and declarative type of language. JavaScript contains a standard library of objects, like Array, Date, and Math, and a core set of language elements like operators, control structures, and statements. 


JavaScript is the Programming Language for the Web.

JavaScript can update and change both HTML and CSS.

JavaScript can calculate, manipulate and validate data.



JavaScript is a high-level, often just-in-time compiled language that conforms to the ECMAScript standard.[11] It has dynamic typing, prototype-based object-orientation, and first-class functions. It is multi-paradigm, supporting event-driven, functional, and imperative programming styles. It has application programming interfaces (APIs) for working with text, dates, regular expressions, standard data structures, and the Document Object Model (DOM).

JavaScript engines were originally used only in web browsers, but are now core components of some servers and a variety of applications. The most popular runtime system for this usage is Node.js.
Although Java and JavaScript are similar in name, syntax, and respective standard libraries, the two languages are distinct and differ greatly in design.

JavaScript is a language that developers use to make interactive webpages. From refreshing social media feeds to displaying animations and interactive maps, JavaScript functions can improve a website's user experience. it is one of the core technologies of the World Wide Web. For example, when browsing the internet, anytime you see an image carousel, a click-to-show dropdown menu, or dynamically changing element colors on a webpage, you see the effects of JavaScript.







-> JavaScript is a dynamic computer programming language.
-> It is lightweight and most commonly used as a part of web pages, whose implementations allow client-side script to interact with the user and make dynamic pages. It is an interpreted programming language with object-oriented capabilities.
-> JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.Complementary to and integrated with HTML.Open and cross-platform
*/

/****   JavaScript Values   ****/
//  -> The JavaScript syntax defines two types of values

/*
    -> Fixed values are called Literals.
    -> Variable values are called Variables.
 */

/**** Using console in javascript ****/

/**** var variable type / box variable name / = assignement / 60 assiged values ****/

// javascript language case-sensitive 

/**************** variable useing var() in javascript *************************/

{
    // var box = "LiveScript"

    // var box_1  = "javascript"

    // var box_2 = 10

    // var box_3 = 20

    // var box_4 = box_2 + box_3



    // console.log(box_4)

    // console.log(box)
    // document.write(box)
    // document.getElementById("demo1").innerHTML = box;   



    // var Names="foo";
    // var names="Javascript";
    // console.log(Names);

    // var number1 = 15;
    // var number2 = 2;
    // console.log(number1 ** number2);

    // var box1="toys";
    // var box1="cloths";
    // var box1 = 45;

    // console.log(box1)

}


// box1 = "apple"
// box1 = 45
// console.log(box1);

/*******New Html Element Add In Though Javascript *********/

{
    // var newelement = document.createElement("h1");
    // newelement.textContent="hello world";
    // document.body.appendChild(newelement);

    // var newelement = document.createElement("marquee" , Option);
    // newelement.textContent="hello world";
    // document.body.appendChild(newelement);

    // var newelement=document.createElement("pre");
    // newelement.textContent="how are you!";
    // document.body.appendChild(newelement);
}

// document.write('hello javascript!');


// js comments

// single-line comments

/* multi-line 
comments */


// Template literals

{
    // var _nameone = "5";
    // var name20 = '5';

    // console.log(name20);

    // console.log(typeof(_nameone))

}


{
    // alert("_nameone + ${name20}")
    // alert(`${_nameone} + ${name20}`); 
}

// Rules for Naming In JavaScript Variables

{
    //valid
    // let a = 'hello';
    // let _a = 'hello';
    // let $a = 'hello';
}
{
    //invalid
    // Let 1a = 'hello'; // this gives an error
}

// JavaScript is case-sensitive. So y and Y are different variables

{
    // let y = "hi";
    // let Y = 5;

    // console.log(y);
    // console.log(Y); 
}

// Keywords cannot be used as variable names.

{
    //invalid
    // let new = 5; // Error! new is a keyword.
}

/*  

Name must start with a letter (a to z or A to Z), underscore( _ ), or dollar( $ ) sign. After first letter we can use digits (0 to 9), for example value1. JavaScript variables are case sensitive, for example x and X are different variables.

*/